[package]
name = "aoc-11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues = "1.0.2"
num-bigint = { version = "0.4" }
num-traits = { version = "*"}